CREATE TABLE bookings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_id   BIGINT,
    full_name    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255),
    booking_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE services
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION,
    CONSTRAINT pk_services PRIMARY KEY (id)
);

ALTER TABLE bookings
    ADD CONSTRAINT uc_bookings_full_name UNIQUE (full_name);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_SERVICE FOREIGN KEY (service_id) REFERENCES services (id);